### ISSUE TITLE
Add HD DMD Panels option (256x64)

### ISSUE THREAD

**Issue by gustavoalara** [DMDTools/artwork4DMD#1]
Hi @ojacques

As some users (like me) have HD matrix panels display, could be very useful if the application could make 128x32 marquees or 256x64 marquees instead of only 128x32 marquees

**Comment by shiryu55** [comment]
I join the request, I have the same model of LED matrices

**Comment by ojacques** [comment]
Done. New settings now allows to output to 128x32 and/or 256x64 and/or any other size.
Output goes to different folders, by size.
